name: Hexo Deploy

on:
  push:
    branches:
      - "main"
jobs:
  pages:
    name: deploy GH pages
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Create RSA
        uses: echo -e "${{ secrets.PUBLIC_KEY }}" >> ~/.ssh/id_rsa
      - name: Copy RSA
        uses: echo -e "Host sdongzhi.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - name: "Execute docker ps via remote host"
        run: ssh root@sdongzhi.com "docker restart darknights_www_web_1"
